spring:
  datasource:
    url: jdbc:mysql://dev-db:3306/Ducktel?useSSL=false
    username: DucktelAdmin
    password: Ducktel123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.ducktelback: DEBUG