spring:
  datasource:
    url: jdbc:mysql://db:3307/Ducktel?useSSL=false&allowPublicKeyRetrieval=true
    username: DucktelAdmin
    password: Ducktel123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.ducktelback: DEBUG
    sun.rmi.transport.tcp: warn
    sun.rmi.loader: warn
    javax.management.remote.rmi: warn