spring:
  datasource:
    url: jdbc:mysql://db:3306/Ducktel?useSSL=false
    username: DucktelAdmin
    password: Ducktel123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    com.ducktelback: INFO